// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQFUjF7_2xJCtcnpYQDxAs7DBtN-qZnU',
    appId: '1:806726850130:web:a96aa002d0f402e86f718b',
    messagingSenderId: '806726850130',
    projectId: 'montra-money',
    authDomain: 'montra-money.firebaseapp.com',
    storageBucket: 'montra-money.appspot.com',
    measurementId: 'G-VSC17GFT7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rE9QwaKK-Xb7grpTpw-kyWmHRmmU0m4',
    appId: '1:806726850130:android:1d40dcad0f5e19026f718b',
    messagingSenderId: '806726850130',
    projectId: 'montra-money',
    storageBucket: 'montra-money.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCspIYp40GoWbPVqlIqYmIocWTvEp4Whq4',
    appId: '1:806726850130:ios:1fd7d127d5c378076f718b',
    messagingSenderId: '806726850130',
    projectId: 'montra-money',
    storageBucket: 'montra-money.appspot.com',
    iosBundleId: 'com.neondevs.montra',
  );

}